//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpProjekat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BpProjekatModelContext : DbContext
    {
        public BpProjekatModelContext()
            : base("name=BpProjekatModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Stamparija> Stamparijas { get; set; }
        public virtual DbSet<Izdavac> Izdavacs { get; set; }
        public virtual DbSet<Striparnica> Striparnicas { get; set; }
        public virtual DbSet<Nagrada> Nagradas { get; set; }
        public virtual DbSet<Kategorija> Kategorijas { get; set; }
        public virtual DbSet<Autor> Autors { get; set; }
        public virtual DbSet<Strip> Strips { get; set; }
        public virtual DbSet<Festival> Festivals { get; set; }
        public virtual DbSet<Izdaje> Izdajes { get; set; }
        public virtual DbSet<Prodaje> Prodajes { get; set; }
        public virtual DbSet<Ucestvuje> Ucestvujes { get; set; }
        public virtual DbSet<Dodeljuje> Dodeljujes { get; set; }
        public virtual DbSet<Crta> Crtas { get; set; }
        public virtual DbSet<Pise> Pises { get; set; }
    }
}
