//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpProjekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dodeljuje
    {
        public int Festival_idf { get; set; }
        public int Nagrada_idn { get; set; }
        public int UcestvujeStrip_idstr { get; set; }
        public int UcestvujeFestival_idf { get; set; }
    
        public virtual Festival Festival { get; set; }
        public virtual Nagrada Nagrada { get; set; }
        public virtual Ucestvuje Ucestvuje { get; set; }
    }
}
