//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpProjekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izdaje
    {
        public int Izdavac_idi { get; set; }
        public int Strip_idstr3 { get; set; }
    
        public virtual Izdavac Izdavac { get; set; }
        public virtual Strip Strip { get; set; }
    }
}
