//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpProjekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodaje
    {
        public int Striparnica_ids { get; set; }
        public int Strip_idstr4 { get; set; }
    
        public virtual Striparnica Striparnica { get; set; }
        public virtual Strip Strip { get; set; }
    }
}
